### ISSUE TITLE
Can't complile under windows with cmake, and MSVC2012 x64, Qt4.8.5

### ISSUE THREAD

**Issue by pauloloid** [romixlab/qmsgpack#1]
Hello,

- I run cmake gui and configure:

	    The C compiler identification is MSVC 17.0.61030.0
		The CXX compiler identification is MSVC 17.0.61030.0
		Check for working C compiler using: Visual Studio 11 2012 Win64
		Check for working C compiler using: Visual Studio 11 2012 Win64 -- works
		Detecting C compiler ABI info
		Detecting C compiler ABI info - done
		Check for working CXX compiler using: Visual Studio 11 2012 Win64
		Check for working CXX compiler using: Visual Studio 11 2012 Win64 -- works
		Detecting CXX compiler ABI info
		Detecting CXX compiler ABI info - done
		Detecting CXX compile features
		Detecting CXX compile features - done
		Qt5 not found, searching for Qt4
		Looking for Q_WS_X11
		Looking for Q_WS_X11 - not found
		Looking for Q_WS_WIN
		Looking for Q_WS_WIN - found
		Looking for Q_WS_QWS
		Looking for Q_WS_QWS - not found
		Looking for Q_WS_MAC
		Looking for Q_WS_MAC - not found
		Found Qt4: C:/qt/qt485-Win64VC11-Slot004/bin/qmake.exe (found version "4.8.5") 
		statusBuilding pack_test
		statusBuilding unpack_test
		statusBuilding mixed_test
		Configuring done

![Screenshot cmake](http://fs2.directupload.net/images/150327/ytanwbb9.jpg)

- I Choose Qt4 Build and click 'configrue' and then I get (in red):

		Qt5 not found, searching for Qt4
		statusBuilding pack_test
		statusBuilding unpack_test
		statusBuilding mixed_test
		Configuring done

- I click 'generate'
- I go to the build dirctory where i open the 'qmsgpack.sln' with MCVS2012 x64 and choose BUILD ALL
- I get these errors:

		
		1>------ Erstellen gestartet: Projekt: ZERO_CHECK, Konfiguration: Debug x64 ------
		2>------ Erstellen übersprungen: Projekt: RUN_TESTS, Konfiguration: Debug x64 ------
		2>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
		1>  Checking Build System
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/CMakeFiles/generate.stamp is up-to-date.
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/src/CMakeFiles/generate.stamp is up-to-date.
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/tests/CMakeFiles/generate.stamp is up-to-date.
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/tests/pack/CMakeFiles/generate.stamp is up-to-date.
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/tests/unpack/CMakeFiles/generate.stamp is up-to-date.
		1>  CMake does not need to re-run because D:/Meeting/qmsgpackneu/qmsgpack-master/build/tests/mixed/CMakeFiles/generate.stamp is up-to-date.
		3>------ Erstellen gestartet: Projekt: qmsgpack, Konfiguration: Debug x64 ------
		4>------ Erstellen übersprungen: Projekt: uninstall, Konfiguration: Debug x64 ------
		4>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
		3>  Building Custom Rule D:/Meeting/qmsgpackneu/qmsgpack-master/src/CMakeLists.txt
		3>  CMake does not need to re-run because D:\Meeting\qmsgpackneu\qmsgpack-master\build\src\CMakeFiles\generate.stamp is up-to-date.
		3>  msgpack.cpp
		3>  msgpack_common.cpp
		3>  pack_p.cpp
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(23): error C2027: Verwendung des undefinierten Typs "QStringList"
		3>          c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/tools/qstring.h(77): Siehe Deklaration von 'QStringList'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(47): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(47): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(47): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(60): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(60): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(60): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(65): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(65): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(65): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(75): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(75): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(75): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(86): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(86): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(86): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(91): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(91): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(91): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(134): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(134): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(134): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(139): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(139): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(139): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(156): error C2027: Verwendung des undefinierten Typs "QStringList"
		3>          c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/tools/qstring.h(77): Siehe Deklaration von 'QStringList'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(156): error C2228: Links von ".length" muss sich eine Klasse/Struktur/Union befinden.
		3>c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/global/qglobal.h(2387): error C2079: 'QForeachContainer<T>::c' verwendet undefiniertes class 'QStringList'
		3>          with
		3>          [
		3>              T=QStringList
		3>          ]
		3>          D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(158): Siehe Verweis auf die Instanziierung der gerade kompilierten Klassen-template "QForeachContainer<T>".
		3>          with
		3>          [
		3>              T=QStringList
		3>          ]
		3>c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/global/qglobal.h(2389): error C2027: Verwendung des undefinierten Typs "QStringList"
		3>          c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/tools/qstring.h(77): Siehe Deklaration von 'QStringList'
		3>c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/global/qglobal.h(2389): error C2146: Syntaxfehler: Fehlendes ';' vor Bezeichner 'i'
		3>c:\qt\qt485-win64vc11-slot004\include\qtcore\../../src/corelib/global/qglobal.h(2389): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(158): error C2039: 'i': Ist kein Element von 'QForeachContainer<T>'
		3>          with
		3>          [
		3>              T=QStringList
		3>          ]
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(178): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(178): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(178): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(183): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(183): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(183): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(220): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(220): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(220): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(225): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(225): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(225): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(249): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(249): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(249): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(254): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(254): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(254): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(315): error C2065: 'uint16_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(315): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ushort'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(315): error C2059: Syntaxfehler: ')'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(320): error C2065: 'uint32_t': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(320): error C2146: Syntaxfehler: Fehlendes ')' vor Bezeichner '_byteswap_ulong'
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(320): error C2059: Syntaxfehler: ')'
		3>  unpack_p.cpp
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(6): error C2065: 'unpack_nil': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(7): error C2065: 'unpack_never_used': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(8): error C2065: 'unpack_false': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(8): error C2065: 'unpack_true': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(9): error C2065: 'unpack_bin8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(9): error C2065: 'unpack_bin16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(9): error C2065: 'unpack_bin32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(10): error C2065: 'unpack_ext8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(10): error C2065: 'unpack_ext16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(10): error C2065: 'unpack_ext32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(11): error C2065: 'unpack_float32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(11): error C2065: 'unpack_float64': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(12): error C2065: 'unpack_uint8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(12): error C2065: 'unpack_uint16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(12): error C2065: 'unpack_uint32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(12): error C2065: 'unpack_uint64': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(13): error C2065: 'unpack_int8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(13): error C2065: 'unpack_int16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(13): error C2065: 'unpack_int32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(13): error C2065: 'unpack_int64': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(14): error C2065: 'unpack_fixext1': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(14): error C2065: 'unpack_fixext2': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(14): error C2065: 'unpack_fixext4': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(14): error C2065: 'unpack_fixext8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(14): error C2065: 'unpack_fixext16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(15): error C2065: 'unpack_str8': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(15): error C2065: 'unpack_str16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(15): error C2065: 'unpack_str32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(16): error C2065: 'unpack_array16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(16): error C2065: 'unpack_array32': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(17): error C2065: 'unpack_map16': nichtdeklarierter Bezeichner
		3>D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\unpack_p.cpp(18): error C2065: 'unpack_map32': nichtdeklarierter Bezeichner
		3>  qmsgpack_automoc.cpp
		3>  Code wird generiert...
		5>------ Erstellen gestartet: Projekt: mixed_test, Konfiguration: Debug x64 ------
		6>------ Erstellen gestartet: Projekt: pack_test, Konfiguration: Debug x64 ------
		5>  Generating mixed_test.moc
		5>  Building Custom Rule D:/Meeting/qmsgpackneu/qmsgpack-master/tests/mixed/CMakeLists.txt
		5>  CMake does not need to re-run because D:\Meeting\qmsgpackneu\qmsgpack-master\build\tests\mixed\CMakeFiles\generate.stamp is up-to-date.
		5>  mixed_test.cpp
		6>  Generating pack_test.moc
		6>  Building Custom Rule D:/Meeting/qmsgpackneu/qmsgpack-master/tests/pack/CMakeLists.txt
		6>  CMake does not need to re-run because D:\Meeting\qmsgpackneu\qmsgpack-master\build\tests\pack\CMakeFiles\generate.stamp is up-to-date.
		6>  pack_test.cpp
		6>D:\Meeting\qmsgpackneu\qmsgpack-master\tests\pack\pack_test.cpp(147): warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
		5>  mixed_test_automoc.cpp
		5>  Code wird generiert...
		5>LINK : fatal error LNK1104: Datei "..\..\src\Debug\qmsgpackd.lib" kann nicht geöffnet werden.
		6>  pack_test_automoc.cpp
		6>  Code wird generiert...
		7>------ Erstellen gestartet: Projekt: unpack_test, Konfiguration: Debug x64 ------
		7>  Generating unpack_test.moc
		7>  Building Custom Rule D:/Meeting/qmsgpackneu/qmsgpack-master/tests/unpack/CMakeLists.txt
		7>  CMake does not need to re-run because D:\Meeting\qmsgpackneu\qmsgpack-master\build\tests\unpack\CMakeFiles\generate.stamp is up-to-date.
		7>  unpack_test.cpp
		7>D:\Meeting\qmsgpackneu\qmsgpack-master\tests\unpack\unpack_test.cpp(51): warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
		7>D:\Meeting\qmsgpackneu\qmsgpack-master\tests\unpack\unpack_test.cpp(54): warning C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.
		7>  unpack_test_automoc.cpp
		7>  Code wird generiert...
		6>LINK : fatal error LNK1104: Datei "..\..\src\Debug\qmsgpackd.lib" kann nicht geöffnet werden.
		7>LINK : fatal error LNK1104: Datei "..\..\src\Debug\qmsgpackd.lib" kann nicht geöffnet werden.
		8>------ Erstellen gestartet: Projekt: ALL_BUILD, Konfiguration: Debug x64 ------
		8>  Building Custom Rule D:/Meeting/qmsgpackneu/qmsgpack-master/CMakeLists.txt
		8>  CMake does not need to re-run because D:\Meeting\qmsgpackneu\qmsgpack-master\build\CMakeFiles\generate.stamp is up-to-date.
		9>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: Debug x64 ------
		9>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
		========== Erstellen: 2 erfolgreich, 4 fehlerhaft, 0 aktuell, 3 übersprungen ==========

Why?

**Comment by pauloleloid** [comment]
Do I need the lib and dll of msgpack?
where should i put it then?

**Comment by pauloleloid** [comment]
I reduced the error list to this, sorry for the german:

Fehler	13	error C2065: 'unpack_uint8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	15	1	qmsgpack
		Fehler	16	error C2065: 'unpack_uint64': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	15	1	qmsgpack
		Fehler	15	error C2065: 'unpack_uint32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	15	1	qmsgpack
		Fehler	14	error C2065: 'unpack_uint16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	15	1	qmsgpack
		Fehler	4	error C2065: 'unpack_true': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	11	1	qmsgpack
		Fehler	26	error C2065: 'unpack_str8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	18	1	qmsgpack
		Fehler	28	error C2065: 'unpack_str32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	18	1	qmsgpack
		Fehler	27	error C2065: 'unpack_str16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	18	1	qmsgpack
		Fehler	1	error C2065: 'unpack_nil': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	9	1	qmsgpack
		Fehler	2	error C2065: 'unpack_never_used': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	10	1	qmsgpack
		Fehler	32	error C2065: 'unpack_map32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	21	1	qmsgpack
		Fehler	31	error C2065: 'unpack_map16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	20	1	qmsgpack
		Fehler	17	error C2065: 'unpack_int8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	16	1	qmsgpack
		Fehler	20	error C2065: 'unpack_int64': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	16	1	qmsgpack
		Fehler	19	error C2065: 'unpack_int32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	16	1	qmsgpack
		Fehler	18	error C2065: 'unpack_int16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	16	1	qmsgpack
		Fehler	12	error C2065: 'unpack_float64': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	14	1	qmsgpack
		Fehler	11	error C2065: 'unpack_float32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	14	1	qmsgpack
		Fehler	24	error C2065: 'unpack_fixext8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	17	1	qmsgpack
		Fehler	23	error C2065: 'unpack_fixext4': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	17	1	qmsgpack
		Fehler	22	error C2065: 'unpack_fixext2': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	17	1	qmsgpack
		Fehler	25	error C2065: 'unpack_fixext16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	17	1	qmsgpack
		Fehler	21	error C2065: 'unpack_fixext1': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	17	1	qmsgpack
		Fehler	3	error C2065: 'unpack_false': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	11	1	qmsgpack
		Fehler	8	error C2065: 'unpack_ext8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	13	1	qmsgpack
		Fehler	10	error C2065: 'unpack_ext32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	13	1	qmsgpack
		Fehler	9	error C2065: 'unpack_ext16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	13	1	qmsgpack
		Fehler	5	error C2065: 'unpack_bin8': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	12	1	qmsgpack
		Fehler	7	error C2065: 'unpack_bin32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	12	1	qmsgpack
		Fehler	6	error C2065: 'unpack_bin16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	12	1	qmsgpack
		Fehler	30	error C2065: 'unpack_array32': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	19	1	qmsgpack
		Fehler	29	error C2065: 'unpack_array16': nichtdeklarierter Bezeichner	D:\Meeting\qmsgpack\qmsgpack-master\src\private\unpack_p.cpp	19	1	qmsgpack


I also try to compile in Qt Creator, with same errors.

**Comment by romixlab** [comment]
Can you test it with QtCreator+MinGW?

**Comment by romixlab** [comment]
Oh, and try to disable testing by commenting out lines 67-68 in CMakeLists.txt

**Comment by pauloleloid** [comment]
I commented lines 67-68 in CMakeLists.txt.
Then I choose MinGw as generator in cmake and these errors appears:

		CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
		CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
		CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
		Missing variable is:
		CMAKE_C_COMPILER_ENV_VAR
		CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
		Missing variable is:
		CMAKE_C_COMPILER
		CMake Error: Could not find cmake module file:D:/Meeting/qmsgpack/test2/qmsgpack-master-build/CMakeFiles/CMakeCCompiler.cmake
		CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
		Missing variable is:
		CMAKE_CXX_COMPILER_ENV_VAR
		CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
		Missing variable is:
		CMAKE_CXX_COMPILER
		CMake Error: Could not find cmake module file:D:/Meeting/qmsgpack/test2/qmsgpack-master-build/CMakeFiles/CMakeCXXCompiler.cmake
		CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
		CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
		-- Configuring incomplete, errors occurred!

Which Version of mingw should I use?

I have the one of Anaconda which is mingw 4.7.
Should i use an older one vor Qt 4.8.5 ?

**Comment by pauloleloid** [comment]
I use a qt485-Win64VC11-build. Is this the reason I can't compile qmsgpack with MinGw?

I would prefer Win 64 VC11 (Visual Studio 2012).

**Comment by romixlab** [comment]
I think it should work with any mingw, that Qt work with...
VS without tests still outputs the same errors?

**Comment by romixlab** [comment]
Also you can try to create a new library project (in vs), add everything from src to it and compile a dll, or simply add all the files to your project tree

**Comment by estan** [comment]
I think your first error with MSVC:

    D:\Meeting\qmsgpackneu\qmsgpack-master\src\private\pack_p.cpp(23): error C2027: Verwendung des undefinierten Typs "QStringList"

Should be fixed now with the merge of #6. Would be interesting to see you try again.

I have a VirtualBox with Windows 7, but it has an old Qt so it's kind of inconvenient to test.

(Perhaps in the future we could do CI on Windows via [Appveyor](http://www.appveyor.com/). I think they have both MinGW and various MSVC versions)

**Comment by romixlab** [comment]
Seems to be fixed with 46f6184f229e8cea66ec63d890548db93ee07b22
