### ISSUE TITLE
msgpack_common.h defines

### ISSUE THREAD

**Issue by anton-dutov** [romixlab/qmsgpack#14]
msgpack_common.h include check defined as

    #ifndef COMMON_H
    #define COMMON_H

but in common style should be

    #ifndef MSGPACK_COMMON_H
    #define MSGPACK_COMMON_H

I have an issue with it, because in our project exists file common.h which has same define

**Comment by romixlab** [comment]
Fixed 4258811d950ead8f45c0c59f06e5196486e4c654
