### ISSUE TITLE
Doesn't compile with qcreator 3.5.1 qt 5.5.1 on windows 8.1

### ISSUE THREAD

**Issue by nikola-v** [romixlab/qmsgpack#16]
Hi,

commenting msgpackcommon.h

----%<--------%<--------%<--------%<----

//#ifdef Q_OS_WINRT
#include <stdint.h>
//#endif

----%<--------%<--------%<--------%<----

makes it compile.

**Comment by romixlab** [comment]
Hello!
Strange, someone added that to solve exactly the same problem... Meybe some more ifdef's is needed here.
