### ISSUE TITLE
Undefined Reference to MsgPackStream

### ISSUE THREAD

**Issue by sebabebibobu** [romixlab/qmsgpack#17]
Hello,

I was able to build qmsgpack with cmake 3.5.0-rc3, mingw493_32 and Qt5.5.1.

The lib (libqmsgpack.a and qmsgpack.dll) is stored in a subdirectory named /lib to the project root (the location where my *.pro file is stored).

I can use MsgPack::pack() and MsgPack::unpack() without problems but when I try to use MsgPackStream the following compiler error appears:

undefined reference to 'MsgPackStream::MsgPackStream(QByteArray const&)
undefined reference to MsgPackStream::~MsgPackStream()
undefined reference to MsgPackStream:~MsgPackStram()
error: ld returned 1 exit status

**Comment by romixlab** [comment]
Hello,
Oh thanks! It seems that I forgot to add MSGPACK_EXPORT in MsgPackStream definition, but in linux it works anyway. Fixed in latest commit 6e023af9e03842c93dd7b5bb1b31513fba6c6d6c
