### ISSUE TITLE
Write bug with QLocalSocket

### ISSUE THREAD

**Issue by mtstickney** [romixlab/qmsgpack#25]
I was just working some fixes to the write support for streams (handling partial writes, like it does partial reads now), and I've come across a bug that probably has to be fixed in qmsgpack, but I'm not sure of the best way to do it.

Here's the bug: QLocalSocket on windows will silently drop data that is written if the previously-written data has not been read on the remote end. E.g.:
````
/* This call will succeed. */
dev->write(data, 1);
/* This call will appear to succeed, but the data is never sent. */
dev->write(data2, 3);
````

The fix is to call `QIODevice::waitForBytesWritten` before a second write happens. The obvious place for this is in `MsgPackStream::writeBytes` after each write, but that's equivalent to calling `flush` on the device, and it's only needed for QLocalSocket.

Do you have any ideas or preferences on how this should be fixed? It's been a long time since I've worked in C++, but my only thought was to have a templated `flushWrite()` method, and somehow arrange to have a version specialized on `QLocalSocket` do the flush and the normal implementation do nothing. I'm not even sure you can actually do that.

**Comment by romixlab** [comment]
Flushing every time could drop performance on streams without that bug. Maybe add waitForBytesWritten(bool wait) and bool field to MsgPackStream? By default set it to false in constructor, so almost every other case will work fast.
