### ISSUE TITLE
solve compiler warnings

### ISSUE THREAD

**Issue by antis81** [romixlab/qmsgpack#28]
There are three compiler warnings, that the expression is always false.

Lines are in msgpackstream.cpp [L340](https://github.com/romixlab/qmsgpack/blob/master/src/msgpackstream.cpp#L340), [L350](https://github.com/romixlab/qmsgpack/blob/master/src/msgpackstream.cpp#L350) and [L512](https://github.com/romixlab/qmsgpack/blob/master/src/msgpackstream.cpp#L512)

Those should be removed (checking on `uint` for negative values).

**Comment by romixlab** [comment]
Oh, actually should be int there. Will fix that, thanks!

**Comment by romixlab** [comment]
Fixed with b7284725e8c84d1ff5fa8210a7436afda7e2dbdc

**Comment by antis81** [comment]
Yeah had a quick look at it. And it looks good, thanks! :)
