### ISSUE TITLE
error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by VictorKozachek** [romixlab/qmsgpack#29]
Hello,

I'm trying to build an example of using your library under Windows 10 and QT Creator.

The library configuration is:
LIBS += -L$$PWD/../../qmsgpack/bin/ -lqmsgpackd

INCLUDEPATH += $$PWD/../../qmsgpack/src
DEPENDPATH += $$PWD/../../qmsgpack/bin

PRE_TARGETDEPS += $$PWD/../../qmsgpack/bin/qmsgpackd.lib

and result of building is:

error LNK2019: unresolved external symbol "__declspec(dllimport) class QVariant __cdecl MsgPack::unpack(class QByteArray const &)" (__imp_?unpack@MsgPack@@YA?AVQVariant@@ABVQByteArray@@@Z) referenced in function "void __cdecl test_float(void)" (?test_float@@YAXXZ)

error LNK2019: unresolved external symbol "__declspec(dllimport) class QByteArray __cdecl MsgPack::pack(class QVariant const &)" (__imp_?pack@MsgPack@@YA?AVQByteArray@@ABVQVariant@@@Z) referenced in function "void __cdecl test_float(void)" (?test_float@@YAXXZ)

fatal error LNK1120: 2 unresolved externals

How to fix it?

Thanks.

Regards,
Victor.

**Comment by VictorKozachek** [comment]
Strange thing

if you replace  
MSGPACK_EXPORT bool registerUnpacker(qint8 msgpackType, unpack_user_f unpacker);
to
 __declspec( dllexport ) bool registerUnpacker(qint8 msgpackType, unpack_user_f unpacker);

it works fine

**Comment by romixlab** [comment]
Hi,
strange, it actually has to be dllimport if you are linking to any library. Check 'Project->Properties->Linker->Input->Additional Dependencies', is there qmsgackd.lib?
If it's not, maybe missing '-L' before $$PWD is the case?

**Comment by VictorKozachek** [comment]
Hi Roman, thanks. 

I will check. Maybe it is a problem of Windows env, because as I can see MSGPACK_EXPORT is equal to __declspec( dllexport )

Maybe I need to focus on Lib tools of windows dev tool. 

Any case, I will check and let you know about result.

Thank you.

**Comment by romixlab** [comment]
Hi Victor, is there any luck with it?
Maybe it's simple - MSGPACK_MAKE_LIB is defined?

**Comment by VictorKozachek** [comment]
Hi, I will try it tomorrow. Just came back home :)
--
Отправлено из Mail.Ru для Android понедельник, 13 ноября 2017г., 22:38 +03:00 от Roman Isaikin  notifications@github.com :

**Comment by VictorKozachek** [comment]
Hi Roman, 

I've tried different scenarios and faced ridiculous results :) 

First of all. My development env is:

Windows 10  (64)
QT version 5.7.1. Static build
QT Creator
qmake

And now the scenarios to build:

**1.** 

1.1. DEFINES += MSGPACK_MAKE_LIB   variable is set
1.2. Header code is:
    MSGPACK_EXPORT  QVariant unpack(const QByteArray &data);
    MSGPACK_EXPORT bool registerUnpacker(qint8 msgpackType, unpack_user_f unpacker);

    MSGPACK_EXPORT QByteArray pack(const QVariant &variant);
    MSGPACK_EXPORT bool registerPacker(int qType, qint8 msgpackType, pack_user_f packer);
    MSGPACK_EXPORT qint8 msgpackType(int qType);

    MSGPACK_EXPORT bool registerType(QMetaType::Type qType, quint8 msgpackType);

    MSGPACK_EXPORT void setCompatibilityModeEnabled(bool enabled);

1.3. #define Q_DECL_EXPORT __declspec( dllexport ) // it's OK

1.4. The build result of test application contains Linker errors: LNK2019

**2.** 

2.1. DEFINES += MSGPACK_MAKE_LIB   variable is set
2.2. Header code is:
    **__declspec( dllexport ) QVariant unpack(const QByteArray &data);**
    MSGPACK_EXPORT bool registerUnpacker(qint8 msgpackType, unpack_user_f unpacker);

    MSGPACK_EXPORT QByteArray pack(const QVariant &variant);
    MSGPACK_EXPORT bool registerPacker(int qType, qint8 msgpackType, pack_user_f packer);
    MSGPACK_EXPORT qint8 msgpackType(int qType);

    MSGPACK_EXPORT bool registerType(QMetaType::Type qType, quint8 msgpackType);

    MSGPACK_EXPORT void setCompatibilityModeEnabled(bool enabled);

2.3. #define Q_DECL_EXPORT __declspec( dllexport ) // it's OK

2.4. The build result of test application..... everything is OK and works fine. :)

It's strange :)

**Comment by romixlab** [comment]
MSGPACK_MAKE_LIB should not be defined if you are just using the library, it is only for the .dll/.so building. Since your Qt build is static, it makes sense to just include all the source files into the project.

Actually @buzzySmile created qmsgpack.pri file for this reason, see a0a1956aecf727b1c1cfc44b17f4a4f77114f186

Nevertheless strange that it builded successfully with dllexport...

**Comment by romixlab** [comment]
Aaand right after that he added MSGPACK_MAKE_LIB ;) 17e7b9f6f961fa665b47b6c78d7e3d7d2ef318a4

**Comment by VictorKozachek** [comment]
:)

If I remove MSGPACK_MAKE_LIB  from DEFINES I can't link your library as static as well.  Strange behavior with last code I sent. I have changed one string of code and it works fine.

Interesting, on Mac OS or Linux it works fine without changes.

**Comment by romixlab** [comment]
Windows...
