### ISSUE TITLE
Create a first release

### ISSUE THREAD

**Issue by estan** [romixlab/qmsgpack#3]
This library looks well written. Would love a first release.

**Comment by estan** [comment]
An alternative if it's always sunny in `master` would be to allow header-only use of the library, like many Boost-ish libraries do. I think this would make it easier to make use of it, and help adoption.

**Comment by romixlab** [comment]
Thanks! There is still missing support for some built in Qt types, and I forgot about thread safety of some functions, so after these fixes it would be a time for the first release, what do you think?

**Comment by estan** [comment]
Sounds good. I've recently used the [Open Build Service](http://build.opensuse.com) to build packages for Ubuntu, openSUSE, Fedora and Arch for a little Qt-based project of mine, so when the time comes and a release tarball is available under "Releases" here on GitHub, I could try to do the same for `qmsgpack`.

**Comment by romixlab** [comment]
That would be great! Thank you!
