### ISSUE TITLE
how to unpack qlist

### ISSUE THREAD

**Issue by sherifomran** [romixlab/qmsgpack#40]
I packed the list as given in the examples
```


    QList<QVariant> list;
    list << 123 << 4.56 << true;
    packed = MsgPack::pack(list);
    qDebug() << packed.toHex();
```

but how to unpack them while holding their types?

**Comment by romixlab** [comment]
Hello!
Use QVariantList u = MsgPack::unpack(packed).toList();
it will contain 3 QVariants with proper types - (QVariant(uint, 123), QVariant(double, 4.56), QVariant(bool, true))
