### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by sherifomran** [romixlab/qmsgpack#41]
when i compile the cmake package, i get a dynamic library, but i hope i can use a static one.
Could you please help me with it.

**Comment by romixlab** [comment]
Sorry for late answer - you can just include all the source files from src similarly to how it is done in https://github.com/romixlab/qmsgpack/blob/master/qmsgpack.pri

**Comment by romixlab** [comment]
Seems like a fix for this - https://github.com/romixlab/qmsgpack/pull/39
