### ISSUE TITLE
Wrong int packing

### ISSUE THREAD

**Issue by jusboa** [romixlab/qmsgpack#46]
The message pack specification says that in32 shall be packed with 0xD2 prefix - see https://github.com/msgpack/msgpack/blob/master/spec.md. However, qmsgpack packs signed integer as unsigned if their value is positive - see src/private/pack_p.cpp, MsgPackPrivate::pack_int.

**Comment by mincequi** [comment]
This behaviour is correct and follows the spec: https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

**Comment by jusboa** [comment]
I believe it does not imply that for signed integer an unsigned integer could be used. For the int32 and unit32 case the number of bytes is the same - so there is no "smallest number of bytes".
