### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by BugZappr** [romixlab/qmsgpack#47]
I"m rockin' Win7 Home x64 SP1, and using Qt Creator 5.02 with Qt 5.15.2.  I have a MSVC 2017 x64 toolchain.

I extract a zip of the latest code, open the .pro file in Qt Creator 5.02, and get the error: 

"LNK1181: cannot open input file 'qmsgpack.lib'"

This is not entirely unsurprising, since it only produces qmsgpack0.lib and qmsgpack0.dll.  Renaming them to qmsgpack.lib and qmsgpack.dll gets the examples to compile and run just fine; after opening the main .pro file in Qt Creator.  Adding `LIBS += -L$$PWD/QMsgPack/qmsgpack.lib` to my project's .pro file and linking to the lib produces a link error:

`mainwindow.obj:-1: error: LNK2019: unresolved external symbol "__declspec(dllimport) class QByteArray __cdecl MsgPack::pack(class QVariant const &)" (__imp_?pack@MsgPack@@YA?AVQByteArray@@AEBVQVariant@@@Z) referenced in function "public: __cdecl MainWindow::MainWindow(class QWidget *)" (??0MainWindow@@QEAA@PEAVQWidget@@@Z)`

Even when I just included the entire source in the project, and tried to compile it, I got that same error!

The commands you give to build and install it "[Installation — qmsgpack 1.0.0rc documentation](https://qmsgpack.readthedocs.io/en/latest/install.html)" don't work on Windows.  For one thing, it uses nmake for MSVC.

It would really be nice to have a MessagePack that knows Qt, so that I don't have to covert everything over to STL containers and data types.  I'd really like to see version 1.00!

**Comment by romixlab** [comment]
The fact that examples run means that you are very close. Probably something wrong with the linking, maybe LIBS don't work as expected?
Try again to include .pri file though, static linking is so much more straight forward.

**Comment by BugZappr** [comment]
I tried static linking; but got similar errors no matter how I tried.  Again, I had to rename the libs for the examples to link; when I shouldn't have to.  FWIW: I've gotten curl, openssl (as a DLL) and qwt to work in a Qt application, which per se doesn't mean I was doing everything right.  To build the static libs, I tried to define MSGPACK_MAKE_LIB or MSGPACK_STATIC in msgpack.h; but neither way worked, as well as having neither.  Including them as source in a project of my own, as I say, didn't work.  I got similar DLL errors there too.

If I include the .pri file, it looks like it expects everything relative to the .pri file's dir.  Some level of testing on my part would probably turn up the discrepancy between my project and your examples; but I hope not to intermingle your files with my project.  If I include the .pri file from my project's home dir, it will be adding those settings relative to my project, not where they are.  It must be close, as you say, for the examples to run.

I recommend, if you don't have a handy Windows environment, checking out the building and usage of yer libs from say, a Windows virtual machine running Qt Creator/Qt, and with, say, the command-line only version of Visual Studio 2017 Build Tools - available free at a modest download size.

I recommend being more clear in your instructions about just how to build on Windows, both as a DLL and as a static lib, and try linking to one or the other from a project in a different dir.  If it just has the Qt Creator instructions, that'll be fine for many, possibly most Qt users.  Better yet, but more work, would be to supply command line commands for building it on Windows.  One complication of that, is probably MSVC and Qt paths and settings would need to be in the same command line environment; and it would probably involve, as above, nmake, not make.  Being multi-platform is, after all, a fairly big thing with Qt.

I do recommend only MSVC on Windows.  Using the mingw version on Windows probably wouldn't impact what you are doing here, but I've found gdb to be unstable on Windows, and crashing frequently.  This may pertain only to a bug in the version supplied with my version of Qt Creator (the last version I could find that worked on Win7).  I've also found gdb to have a lesser ability to show me the values of all my variables when debugging; which pre-dated the crashing issue.

I may just be doing something wrong, but I am sure the libs I built and my project I tried to use them in were both for x64 and were Release builds.  I suspect it may take several rounds of us going back and forth here if I do the Windows testing, but a fairly quick thing if your do.  Writing detailed instructions on how to incorporate it into a Qt project in another directory on Windows would also be helpful.

I suspect if you got a Windows build environment set up for yourself, you would make pretty quick work of it.  Writing detailed instructions on how to incorporate it into a Qt project in another directory on Windows would also be helpful; which you might do in the process.  I know, other packages such as curl and openssl don't bother to; but such instructions would probably be pretty short, assuming one has a Qt build environment on Windows already.  I do readily advocate for Linux gurus to be more helpful in their instructions, as more than occasionally, the ethic of terse instructions (and especially not anticipating common errors in them relating to the software, or not having examples, although you do) more than occasionally costs users a lot of time, when it might be considerably easier for the devs..

**Comment by BugZappr** [comment]
I tried static linking; but got similar errors no matter how I tried.  Again, I had to rename the libs for the examples to link; when I shouldn't have to.  FWIW: I've gotten curl, openssl (as a DLL) and qwt to work in a Qt application, which per se doesn't mean I was doing everything right.  To build the static libs, I tried to define MSGPACK_MAKE_LIB or MSGPACK_STATIC in msgpack.h; but neither way worked, as well as having neither.  Including them as source in a project of my own, as I say, didn't work.  I got similar DLL errors there too.

If I include the .pri file, it looks like it expects everything relative to the .pri file's dir.  Some level of testing on my part would probably turn up the discrepancy between my project and your examples; but I hope not to intermingle your files with my project.  If I include the .pri file from my project's home dir, it will be adding those settings relative to my project, not where they are.  It must be close, as you say, for the examples to run.

I recommend, if you don't have a handy Windows environment, checking out the building and usage of yer libs from say, a Windows virtual machine running Qt Creator/Qt, and with, say, the command-line only version of Visual Studio 2017 Build Tools - available free at a modest download size.

I recommend being more clear in your instructions about just how to build on Windows, both as a DLL and as a static lib, and try linking to one or the other from a project in a different dir.  If it just has the Qt Creator instructions, that'll be fine for many, possibly most Qt users.  Better yet, but more work, would be to supply command line commands for building it on Windows.  One complication of that, is probably MSVC and Qt paths and settings would need to be in the same command line environment; and it would probably involve, as above, nmake, not make.  Being multi-platform is, after all, a fairly big thing with Qt.

I do recommend only MSVC on Windows.  Using the mingw version on Windows probably wouldn't impact what you are doing here, but I've found gdb to be unstable on Windows, and crashing frequently.  This may pertain only to a bug in the version supplied with my version of Qt Creator (the last version I could find that worked on Win7).  I've also found gdb to have a lesser ability to show me the values of all my variables when debugging; which pre-dated the crashing issue.

I may just be doing something wrong, but I am sure the libs I built and my project I tried to use them in were both for x64 and were Release builds.  I suspect it may take several rounds of us going back and forth here if I do the Windows testing, but a fairly quick thing if your do.  Writing detailed instructions on how to incorporate it into a Qt project in another directory on Windows would also be helpful.

I suspect if you got a Windows build environment set up for yourself, you would make pretty quick work of it.  Writing detailed instructions on how to incorporate it into a Qt project in another directory on Windows would also be helpful; which you might do in the process.  I know, other packages such as curl and openssl don't bother to; but such instructions would probably be pretty short, assuming one has a Qt build environment on Windows already.  I do readily advocate for Linux gurus to be more helpful in their instructions, as more than occasionally, the ethic of terse instructions (and especially not anticipating common errors in them relating to the software, or not having examples, although you do) more than occasionally costs users a lot of time, when it might be considerably easier for the devs.

**Comment by romixlab** [comment]
Unfortunately I do not have time to work on this project nowadays. I hope you've found a solution for your project and that this library was of any help.

**Comment by BugZappr** [comment]
Too bad.  I guess I'll be working with JSON for Modern C++; but unfortunately, I'll have to convert everything back and forth between STL and Qt types.  It seems you completed it 98%+, but quit before the final 2% to complete version 1.0.  The built-in QJsonObject doesn't support binary without re-encoding, nor MessagePack.  I can understand about being busy; and so would like to ask you to post something in your Readme.md that you are no longer maintaining it; but encourage others to fork it, and pick up with it where you left off.
