### ISSUE TITLE
Fix / document thread-safety

### ISSUE THREAD

**Issue by estan** [romixlab/qmsgpack#5]
At the moment, it looks like the library has some global data (compat mode, the hash of user packers), which makes me guess the library is not thread safe? It would be great if it were. Until then, it would at least be nice if the thread-unsafetyness was documented in `README.md`.

**Comment by romixlab** [comment]
I think it will not be a problem... Now when the lib can help someone, I will continue to work on it!
Modified readme for now.

**Comment by estan** [comment]
Thanks. Yes, it sounds like it should be safe if you're careful to not use those functions from multiple threads. I think you might have missed a few words in `README.md`:

    [...] different threads. pack and unpack methods do not use any global data, so

should be

    [...] different threads. pack and unpack methods do not use any global data, so should be safe to use from multiple threads.

**Comment by romixlab** [comment]
Oh, yep
